### ISSUE TITLE
`async` possibility when using FMU sumo explorer

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-sumo#156]
Currently with `fmu-sumo` explorer (I think) you are enforced to run it synchronously.

In multi-user backend context (web server) it would be nice/important that `fmu-sumo` can do the underlying requests to the SUMO service `async`, and that the consumer code can `await`.

**Comment by anders-kiaer** [comment]
This issue perhaps is equally relevant for `sumo-wrapper-python`. I see `requests` is used (https://github.com/equinor/sumo-wrapper-python/blob/main/src/sumo/wrapper/sumo_client.py). A popular Python library which follows `requests` API is `httpx` (https://www.python-httpx.org/) - maybe it is almost a drop-in-replacement for `requests` for the use cases here? (https://www.python-httpx.org/compatibility/)

I guess two possible solutions are on the table for SUMO:
- sumo-explorer move to `async` offering only (the user of notebooks then need to `await`).
- sumo-explorer supports both `sync` and `async` (the user could choose when using `sumo` explorer if he/she wants sync or async behaviour)

**Comment by equinor-ruaj** [comment]
sumo-explorer [0.3.11](https://github.com/equinor/fmu-sumo/releases/tag/0.3.11) released with async methods, e.g. `get_case_by_uuid_async` (note the `_async` suffix)
Note that it is dependent on `sumo-wrapper-python>=0.3.5`

**Comment by equinor-ruaj** [comment]
Have you been able to test this @anders-kiaer ?
