### ISSUE TITLE
Simulation results tables exported with metadata

### ISSUE THREAD

**Issue by AishaAiak** [equinor/fmu-sumo#202]
Enable users to add an optional argument e.g. --metadata to their existing ecl2df calls, then use fmu-dataio under the hood to create metadata on export.

 Acceptance Criteria
User can add optional argument --metadata (or similar) to their existing ecl2df calls in ERT config, then metadata is produced for outgoing tables.

- [x] Add ecl2df as a utility in fmu-sumo -> #197 

- [x] Confirm with a Snorre case

- [ ] Feedback from "someone" from Castberg

- [ ] Feedback from Øyvind

- [ ] Feedback from Rosebank

- [ ] Define missing data.content

- [ ] Feedback from JS (Marie Louise/Richy)

**Comment by equinor-ruaj** [comment]
Done with some small known issues that will be followed up in separate tasks. Closing.
