### ISSUE TITLE
Content of parameters.txt available to data consumers

### ISSUE THREAD

**Issue by adnejacobsen** [equinor/fmu-sumo#203]
Discussion: https://equinor.slack.com/archives/C0152LS9TTP/p1686565753823709

To be refined

- [ ] Upload parameters.txt and metadata from uploader

**Comment by adnejacobsen** [comment]
While working on this issue and testing the code I ran the same case multiple times with everything except the `SUMO_UPLOAD` jobs commented out. At one point `parameters.txt` was replaced with `parameters.txt_backup_2023-09-05_13-48-18Z`. This would probably not happen if I didn't run ERT in an existing runpath, which I'm guessing users are not supposed to do. Should we handle this and use whatever file matches `parameters.txt*` or should the uploading not proceed if `parameters.txt` does not exist? Any thoughts @perolavsvendsen @daniel-sol?

**Comment by perolavsvendsen** [comment]
I think ERT is communicating some intentions here by explicitly changing the filename, so my gut feeling is that we fetch it if it is there and called `parameters.txt`, else do nothing. Down the line when we know more we should coordinate with ERT on how to get the contents of `parameters.txt`.
