### ISSUE TITLE
Enable uploader logging for Sumo

### ISSUE THREAD

**Issue by AishaAiak** [equinor/fmu-sumo#206]
- [ ] Establish logging to Sumo
- [ ] How much log(to be refined) ??

**Comment by roywilly** [comment]
Here is an example of how it looks in swagger GET message-log:
   "hits": [
      {
        "_index": "sumomessagelog",
        "_id": "Or_SjYoB_5PhkKrbOgPA",
        "_score": null,
        "_source": {
          "severity": "INFO",
          "linenumber": 349,
          "funcname": "upload_to_sumo",
          "radix_pod_id": "66c9dbd5b4",
          "sumo_env": "dev",
          "source": "sumo.fmu.uploader.logger",
          "authenticated_user": "ROWH@equinor.com",
          "message": "HelloWorld1922INFO2",
          "timestamp": "2023-09-13T09:14:18Z",
          "radix_replica_id": "mvzq4",
          "pathname": "C:\\Appl\\repos\\fmu-sumo\\src\\fmu\\sumo\\uploader\\_fileondisk.py"
        },
        "sort": [
          1393093
        ]
      }

**Comment by roywilly** [comment]
PR #212  (https://github.com/equinor/fmu-sumo/pull/212)
