### ISSUE TITLE
Aviod missing blob

### ISSUE THREAD

**Issue by AishaAiak** [equinor/fmu-sumo#207]
- [ ] Why, we are missing blobs?

**Comment by roywilly** [comment]
Stress-testing of RGS on Azure showed a few errors in the uploader logs where OpenVDS import failed with 403 error, and it seemed seismic metadata existed, but not the actual data in Storage Account. Simulating SAS token timeout by adding sleep in the uploader code for seismic shows that the metadata is actually removed after a failed openvds upload, at least in a normal situation: https://github.com/equinor/fmu-sumo/blob/ad21f6d640febd2179feb4f7f0bc7c483b9c5ff8/src/fmu/sumo/uploader/_fileondisk.py#L342  
Keeping this uploader functionality as-is.

**Comment by roywilly** [comment]
Reading Drogon in DEV seismic/cube metadata objects and verifying seismic files exists in Storage Account:
Found 72046 metadata objects and 24 of those were missing files. 
Most of the cases were created by rowh, 1 by hakal. 
All 24 had 0 files except 1 which had 73 files (instead of the expected 75 files).
3 cases from the stress-testing with new RGS Azure. 
2 cases from 30 aug. 
hakal case from 31 aug.

**Comment by roywilly** [comment]
The details from reading all seismic/cube in Drogon DEV comment above:
 DIFFERS!rowh_simul_500_anf_01_az_drogon_design 5d25e525-2e6e-45ca-bc33-44f78c80520d cube: 359e3af5-511a-ea59-f1c2-00fcc6f6adff  num_seismic_blobs: 73
 DIFFERS!rowh_07_az_lustre_drogon_design f5359bd3-09fc-4bd4-b7bf-9a09b3ae6247 cube: 73e2a8df-83fc-ebd0-97d6-8d1aa42582ff  num_seismic_blobs: 0
 DIFFERS!rowh_07_az_lustre_drogon_design f5359bd3-09fc-4bd4-b7bf-9a09b3ae6247 cube: f66dbfa5-5ec7-c79b-f7e9-d0f8e33dbcb4  num_seismic_blobs: 0
 DIFFERS!webviz_case_1 b0421a97-3965-4d21-9265-d560aa56e1ef cube: 0cb32c69-5b08-1359-56a5-cb8dda3ce103  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: 577d3d61-e260-17a8-b823-f61554b8129e  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: 85c8c842-f3b7-e852-76ea-1ff035022e67  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: f1806f47-c66c-e9c5-78d8-ef9450ae429e  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: e73a97d1-6e0c-b297-3d60-f8c9dac56902  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: 3d7522e9-b09e-c53e-a225-0a814725b934  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: 0c487586-d7b1-7b9f-adc6-7615dd7497ba  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: 6a263d89-b6f7-f182-01ef-910255701364  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: 6172b66a-9fad-edbf-5eef-640acc1601f6  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: f4b04fb1-d282-fd2b-249f-2444b9983933  num_seismic_blobs: 0
 DIFFERS!after_mob_drogon_design eb98890a-e5f3-419a-85ec-3ed25e9fc9de cube: 9b0b573a-e45d-5684-6bd0-0f2f6d291f9c  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: 2116adcd-0693-9a21-2c3f-3a0d2d741eac  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: 6503caca-2c89-0ca5-135b-e2a7348442f5  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: f0e841e9-de3e-dd06-9498-dac95e08120b  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: 9660f8c2-be69-c7e4-46f3-2f503b86265a  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: fba33e85-2b07-0580-f909-a4c4ff97f3d7  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: cfb0b03c-4933-e3d4-84e2-27b5cec2b4bc  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: c3ca90f1-a781-f218-baa5-c0b7057dad0a  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: 317d6544-b24c-22b8-c1f5-460a03e1b562  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: 6633d4c1-d46c-b1a6-069e-01de68715a52  num_seismic_blobs: 0
 DIFFERS!mob_drogon_design 8996d1ef-6d22-437d-b4ee-dfe7450d814d cube: c050b065-77dd-3f82-9805-15afd88eea90  num_seismic_blobs: 0
Total cubes: 72046
Total differs: 24
