### ISSUE TITLE
Bigger refactoring of uploader

### ISSUE THREAD

**Issue by AishaAiak** [equinor/fmu-sumo#208]
Refinement 11/09/23

Ref to US: https://dev.azure.com/Equinor/Sumo/_backlogs/backlog/Sudo%20Team/Epics/?workitem=355460

- [ ] exploration 
- [ ] should fmu data-io do uploading ???
- [ ] Sumo connection need to tidy up??

**Comment by equinor-ruaj** [comment]
[#a10fa07](https://github.com/equinor/fmu-sumo-uploader/commit/a10fa07) closes
