### ISSUE TITLE
Installable on Windows

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo#214]
Currently does not install on Windows.

- Downloads _every single version_ of multiple packages from pypi
- Stops at conflicts related to ERT

Can we avoid installing ERT on Windows? Windows use case is limited to the `explorer`.
Is this penalty for having the explorer and the uploader in the same package?

**Comment by roywilly** [comment]
Moved sim2sumo to new repo fmu-sumo-sim2sumo (and currently adding it to komodo 2023.10)
Moved uploader to new repo fmu-sumo-uploader (will add to komodo later)
Removed ert and ecl2df from requirements of fmu-sumo. 
fmu-sumo now can run tests on windows, ubuntu and macos
