### ISSUE TITLE
Split fmu-sumo into separate repositories

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo#215]
Currently, both the `explorer`, the `uploader` and the `utilities` are in the same repository. This may not scale very well, as seen in e.g. #214. In general, the modules does not share code, but share requirements. While the uploader is depending on packages only available on Unix, the explorer needs to run on Windows.

- Should this repository be broken up into separate repos?
  - fmu-sumo-explorer (namespace: `fmu.sumo.explorer`)
  - fmu-sumo-uploader (namespace: `fmu.sumo.uploader`)
  - fmu-sumo-sim2sumo (namespace: `fmu.sumo.sim2sumo`) (?)

**Comment by AishaAiak** [comment]
Refinement 25/09/23

1: fmu-sumo stay as is
2: Explorer in wrapper repo
3: Split Explorer, uploader and wrapper. Keep utilities with uploader

Uploader outside the ERT context?? 

Keep explorer in fmu-sumo and take uploader and sim2sumo out from fmu-sumo??
split between sim2sumo and uploader??

fmu-sumo keeps explorer and break uploader and sim2sumo in seperate repos. Means pip install fmu-sumo would install explorer only. 

- [ ] split out uploader into own repo fmu-sumo-uploader (namespace: fmu.sumo.uploader)
  - [ ] Need to update komodo, add this to komodo
  - [ ] built uploader from scratch and switch later to it???

- [ ] split out sim2sumo into own repo fmu-sumo-sim2sumo (namespace: fmu.sumo.sim2sumo)(can be bucket in future?)
  - [ ] Add this dependency to

**Comment by AishaAiak** [comment]
- [ ] github issues for new repos

**Comment by equinor-ruaj** [comment]
Repositories split. Closing.
