### ISSUE TITLE
Expand test matrix

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo#218]
Should test on 3.8, 3.9, 3.10 and 3.11.
Should test on Unix, Windows and Mac.

Will require some rebuilding of the tests, enable parallel tests.

**Comment by roywilly** [comment]
Upload tests moved to new repo fmu-sumo-uploader and there changed to run in parallell. 
Excluded OpenVDS imports and tests in fmu-sumo repo.
