### ISSUE TITLE
Functionality for observation data?

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo#242]
FMU observation data are stored as tables with context case. Do we need any extra functionality in the explorer for these datatypes?

**Comment by HansKallekleiv** [comment]
Have a working [PR ](https://github.com/equinor/webviz/pull/432/files#diff-84e353e41344ff087eea7c600ba373f234e069fdc361d53322aefb173420a03eR19)in webviz for retrieving observations using fmu-sumo.
I think we have what we need from our side atleast👍
