### ISSUE TITLE
Timeout whilst iterating over case surfaces

### ISSUE THREAD

**Issue by SteffenEq** [equinor/fmu-sumo#253]
Hi,

I am using `from fmu.sumo.explorer import Explorer` to iterate through surfaces and collect metadata. I experience problems for some cases that have large number of surfaces. Trying to split up the workload still fails. Is there a better way to split up the data retrieval to avoid (what I assume is timeout in httpx?) exception?

Goal: Be able to iterate and read metadata for all surfaces in a specific case.

MRE (potentially sensitive data is obmitted):
```python
from fmu.sumo.explorer import Explorer
explorer = Explorer(token=TOKEN)
case = explorer.cases.filter(field=FIELD, name=LARGE_CASE_WITH_35K_SURFACES)
surfaces = case[0].surfaces.filter(name=SURFACE_NAME) 
print("Number of surfaces", len(surfaces))  # Returns e.g. 1632
surface_uuid = [surface.uuid for surface in surfaces]  # Fails 1/4 times: IndexError in surface_collection.py", line 41, in __getitem__
print("Number of surface uuids", len(surface_uuid))
```

Stack trace:
```terminal
Traceback (most recent call last):
  File "test_sumo.py", line 9, in <module>
    surface_uuid = [surface.uuid for surface in surfaces]  # Fails 1/4 times: IndexError in surface_collection.py", line 41, in __getitem__
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "test_sumo.py", line 9, in <listcomp>
    surface_uuid = [surface.uuid for surface in surfaces]  # Fails 1/4 times: IndexError in surface_collection.py", line 41, in __getitem__
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fmu\sumo\explorer\objects\_document_collection.py", line 39, in __next__
    res = self.__getitem__(self._curr_index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fmu\sumo\explorer\objects\surface_collection.py", line 41, in __getitem__
    doc = super().__getitem__(index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fmu\sumo\explorer\objects\_document_collection.py", line 95, in __getitem__
    raise IndexError
IndexError
```

Thanks!

**Comment by equinor-ruaj** [comment]
When iterating over large datasets you should specify a `keep_alive` for the explorer e.g. `Explorer(keep_alive="2m")`.

We would also recommend that you filter case based on `uuid` instead of `name`, as Sumo does not require names to be unique.

**Comment by SteffenEq** [comment]
Thank you @equinor-ruaj! The `keep_alive` parameter is just what I needed. My apologies for not finding this on my own.

And yes we do, in general use uuids. My example above was a bit hasteful

Thanks again,
Have a good day!
