### ISSUE TITLE
Should the Explorer exclude instead of include metadata fields?

### ISSUE THREAD

**Issue by equinor-ruaj** [equinor/fmu-sumo#260]
The current implementation of the Explorer specifies which metadata to **include** when getting data.
Should we instead specify what to **exclude**?

This would mean that "all" metadata is available through the Explorer if we do not specifically exclude it.

**Comment by ashildskalnes** [comment]
Yes, please:-)

**Comment by equinor-ruaj** [comment]
#268 adds more metadata
