### ISSUE TITLE
TableCollection.columns does not return all unique values

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/fmu-sumo#261]
Most likely a very generic problem, but using this specifically as it is reported by several webviz users.
This is expected to return all unique column names for a given table: https://github.com/equinor/fmu-sumo/blob/8164d5f173084e7798d5c1b98983af142306ef5f/src/fmu/sumo/explorer/objects/table_collection.py#L39 

But I believe it ends up being limited to 2000 results here.
https://github.com/equinor/fmu-sumo/blob/8164d5f173084e7798d5c1b98983af142306ef5f/src/fmu/sumo/explorer/_utils.py#L31

Some of the FMU tables can have 10000+ columns, so this is limitation is a bit dangerous.

I'm not sure of the best solution here. Increasing the size might work for this use case, but there might be other unknown use cases that have much higher unique results.

Is it possible to run an explorative query first, e.g. with cardinality aggregation to get the approximate size?
Or alternatively some pagination, e.g. using `sum_other_doc_count`?
Or have it as metadata somehow?

**Comment by rwiker** [comment]
Do you actually want to have a list of >1000 names returned, or do you want to have a filtering mechanism as well?

**Comment by HansKallekleiv** [comment]
We want the full list. We do filtering and organizing when we have the list, but I don't think we want that logic in here.
That will be very domain specific and vary between different tables (summary, inplace, etc).
