### ISSUE TITLE
Inconsistent patter: to_pandas should be a function

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo#267]
While `to_regular_surface` and `to_arrow` are functions, `to_pandas` is a property. This results in inconsistent code pattern, not intuitive to the user.

e.g.

```python
mytable = mycase.tables[0]
mytable.to_pandas # not a function

mysurface = mycase.surfaces[0]
mysurface.to_regular_surface() # function
```

![image](https://github.com/equinor/fmu-sumo/assets/35033325/4c318be5-3836-449f-9791-0568cee208af)

https://github.com/equinor/fmu-sumo/blob/c87b385bce481f64f456462c25c5605c4a2a615c/src/fmu/sumo/explorer/objects/table.py#L40

How to best change this? It will be breaking change if changed directly.

**Comment by equinor-ruaj** [comment]
#272 closes
