### ISSUE TITLE
Tests does not run out of the box

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo#271]
When cloning this repository, installing with `dev` dependencies, running `pytest`, I get the following:

```
ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
```

**Comment by perolavsvendsen** [comment]
Simply importing `requests` will reproduce this:

```python
import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/peesv/bin/sumo/fmu-sumo/_venv/lib64/python3.8/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/private/peesv/bin/sumo/fmu-sumo/_venv/lib64/python3.8/site-packages/urllib3/__init__.py", line 41, in <module>
    raise ImportError(
ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
```

Using latest version (`2.31.0`) of `requests`.

**Comment by roywilly** [comment]
There is a known OpenSSL related issue on urllib3 v2 on RHEL 7, so komodo team ensures we are on older urllib3 until RHEL8: see their details here: [https://github.com/equinor/komodo-releases/blob/1f89d125f0ab27c6629102c7ecf2a508f95c5847/releases/matrices/bleeding.yml#L351](https://github.com/equinor/komodo-releases/blob/1f89d125f0ab27c6629102c7ecf2a508f95c5847/releases/matrices/bleeding.yml#L351)


I am not able to recreate this issue on my Windows laptop, PY3.9, create new venv:
- pip install .[dev]
- pytest
- Runs as expected. 
- pip list gives: requests  2.31.0 and urllib3  2.2.1

RGS, komodo stable, komodoenv (m3 + 2024.02.12-py38-rhel7): 
- fmu-sumo already installed by default
- pip install pytest
- pytest
- Runs as expected
- pip list gives: requests 2.31.0 and urllib3 1.26.18

Not sure how to set up an environment that triggers this problem: python3 venv on RHEL7 but not komodo?

We could demand a lower version for fmu-sumo in the toml-file, but I assume that could give other problems on other platforms, and also we would have to remember to edit the toml.file again when RHEL7 is out. 

Propose to not leave as is.
