### ISSUE TITLE
Sort iteration according to human logic

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo#280]
Iteration names are now sorted according to machine logic.
 E.g :
 
` pred-1, pred-100, pred-2, pred-3`
 
 For a human it is desirable with logic:
`pred-1, pred-2, pred-3, pred-100`

**Comment by perolavsvendsen** [comment]
There is no standard on iteration (ensemble) names. It is a mix of conventions and free text. (E.g. does the pattern described above (pred-1, pred-2, etc) exist outside Troll?)

It is difficult to find a universal rule that will work.

Example: `iter-0`, `iter-2`, `iter-10`, `pred`.
Example: `iter-0`, `iter-2`, `pred-1`, `pred-2`, `pred-10`.
Example: `myiter`, `myotheriter`, `final`, `first`, `test`
------------

Trying to sort on `name` I think could quickly explode into quite a lot of code. Perhaps better to sort on datetime? First created, first listed?
