### ISSUE TITLE
The `Case.iterations_async` property does not return all iterations

### ISSUE THREAD

**Issue by sigurdp** [equinor/fmu-sumo#326]
There seems to be a bug in the aggregation implementation in `Case.iterations_async` which causes far too few iterations to be returned.
This can be observed for the case `9c9d9a52-1cf4-44cc-829f-23b8334ae813` which should be returning 33 iterations, but only returns 2.

As of now, the sync implementation seems to return the right result.

On a related note, the current implementation seems to have a limit of returning 50 unique iterations. The case mentioned above is already at 33 iterations, so it might make sense to increase this value as well.

**Comment by equinor-ruaj** [comment]
#343 should fix.
