### ISSUE TITLE
Increase performance when reading inplace (volume) data

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo#97]
Proxy-issue for other elements in Sumo, but as discussed Oct 26 2022, performance when fetching 100+ individual files containing inplace volume data is not at minimum viable level. Need to increase performance. Elements that have been mentioned:

- Aggregate data prior to upload
- Aggregate data post upload, but before consumption
- Aggregate data on download (service for getting data). To be seen in relations to #96 to ensure that performance can be increased iteratively without having to rewrite the fetching of data in e.g. Webviz.

**Comment by anders-kiaer** [comment]
With the table aggregation functionality I think we can say this is now closed?
